from __future__ import annotations

from typing import Protocol

from jarvis_automation.models import (
    ApprovalRequest,
    AutomationPolicy,
    AutomationPolicyScope,
    ExecutionContextData,
    MonitoringReport,
    RetryPolicy,
    ScheduleDefinition,
    StepState,
    TriggerDefinition,
    TriggerEvent,
    TriggerType,
    VariableScope,
    VariableValue,
    WorkflowDefinition,
    WorkflowExecutionRequest,
    WorkflowExecutionResult,
    WorkflowExecutionState,
    WorkflowHealthReport,
    WorkflowMetadata,
    WorkflowStatus,
)


class WorkflowRegistry(Protocol):
    def register(self, definition: WorkflowDefinition) -> WorkflowMetadata: ...
    def update(self, metadata: WorkflowMetadata) -> None: ...
    def get(self, workflow_id: str) -> WorkflowMetadata | None: ...
    def list(self) -> tuple[WorkflowMetadata, ...]: ...
    def list_by_status(self, status: WorkflowStatus) -> tuple[WorkflowMetadata, ...]: ...
    def list_by_category(self, category: str) -> tuple[WorkflowMetadata, ...]: ...
    def deregister(self, workflow_id: str) -> None: ...


class StateManager(Protocol):
    def create(self, execution_id: str, workflow_id: str) -> WorkflowExecutionState: ...
    def get(self, execution_id: str) -> WorkflowExecutionState | None: ...
    def update_status(
        self, execution_id: str, status: WorkflowStatus
    ) -> WorkflowExecutionState: ...
    def update_step(
        self, execution_id: str, step_state: StepState
    ) -> WorkflowExecutionState: ...
    def set_current_step(
        self, execution_id: str, step_id: str
    ) -> WorkflowExecutionState: ...
    def list_by_status(
        self, status: WorkflowStatus
    ) -> tuple[WorkflowExecutionState, ...]: ...


class ExecutionContext(Protocol):
    def create(
        self, workflow_id: str, execution_id: str,
        correlation_id: str, workspace: str, project: str,
    ) -> ExecutionContextData: ...
    def get(self, execution_id: str) -> ExecutionContextData | None: ...
    def advance_step(self, execution_id: str, step_id: str) -> ExecutionContextData: ...
    def get_history(self, execution_id: str) -> tuple[str, ...]: ...


class VariableManager(Protocol):
    def set(self, execution_id: str, variable: VariableValue) -> None: ...
    def get(self, execution_id: str, name: str) -> VariableValue | None: ...
    def list(self, execution_id: str) -> tuple[VariableValue, ...]: ...
    def list_by_scope(
        self, execution_id: str, scope: VariableScope
    ) -> tuple[VariableValue, ...]: ...
    def delete(self, execution_id: str, name: str) -> None: ...


class RetryManager(Protocol):
    def should_retry(self, step_id: str, policy: RetryPolicy, attempts: int) -> bool: ...
    def next_delay(self, policy: RetryPolicy, attempts: int) -> int: ...
    def record_attempt(self, execution_id: str, step_id: str) -> int: ...
    def get_attempts(self, execution_id: str, step_id: str) -> int: ...
    def reset(self, execution_id: str, step_id: str) -> None: ...


class CompensationEngine(Protocol):
    def register_compensation(self, execution_id: str, step_id: str, action_id: str) -> None: ...
    def compensate(self, execution_id: str, failed_step_id: str) -> tuple[str, ...]: ...
    def get_compensation_order(self, execution_id: str) -> tuple[str, ...]: ...


class ApprovalEngine(Protocol):
    def request_approval(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def approve(self, approval_id: str, approver: str) -> ApprovalRequest: ...
    def reject(self, approval_id: str, approver: str) -> ApprovalRequest: ...
    def get_request(self, approval_id: str) -> ApprovalRequest | None: ...
    def list_pending(self, execution_id: str) -> tuple[ApprovalRequest, ...]: ...
    def is_approved(self, approval_id: str) -> bool: ...


class SchedulerEngine(Protocol):
    def register_schedule(self, schedule: ScheduleDefinition) -> None: ...
    def unregister_schedule(self, schedule_id: str) -> None: ...
    def get_schedule(self, schedule_id: str) -> ScheduleDefinition | None: ...
    def list_schedules(self) -> tuple[ScheduleDefinition, ...]: ...
    def list_due(self) -> tuple[ScheduleDefinition, ...]: ...


class TriggerEngine(Protocol):
    def register_trigger(self, trigger: TriggerDefinition) -> None: ...
    def unregister_trigger(self, trigger_id: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> TriggerDefinition | None: ...
    def list_triggers(self) -> tuple[TriggerDefinition, ...]: ...
    def list_by_type(self, trigger_type: TriggerType) -> tuple[TriggerDefinition, ...]: ...
    def fire(self, event: TriggerEvent) -> tuple[WorkflowExecutionRequest, ...]: ...


class PolicyEngine(Protocol):
    def register_policy(self, scope: AutomationPolicyScope, policy: AutomationPolicy) -> None: ...
    def resolve(self, scope: AutomationPolicyScope) -> AutomationPolicy: ...
    def evaluate(self, workflow_id: str, policy: AutomationPolicy) -> tuple[str, ...]: ...


class MonitoringEngine(Protocol):
    def record_execution(
        self, workflow_id: str, execution_id: str, status: WorkflowStatus,
    ) -> MonitoringReport: ...
    def record_step_completion(
        self, execution_id: str, step_id: str, duration_ms: int, success: bool,
    ) -> None: ...
    def get_workflow_health(self, workflow_id: str) -> WorkflowHealthReport | None: ...
    def list_health_reports(self) -> tuple[WorkflowHealthReport, ...]: ...
    def list_unhealthy(self) -> tuple[WorkflowHealthReport, ...]: ...


class WorkflowEngine(Protocol):
    def start(self, request: WorkflowExecutionRequest) -> WorkflowExecutionResult: ...
    def pause(self, execution_id: str) -> WorkflowExecutionResult: ...
    def resume(self, execution_id: str) -> WorkflowExecutionResult: ...
    def cancel(self, execution_id: str) -> WorkflowExecutionResult: ...
    def get_status(self, execution_id: str) -> WorkflowExecutionState | None: ...
    def get_result(self, execution_id: str) -> WorkflowExecutionResult | None: ...


class AutomationKernel(Protocol):
    def register_workflow(self, definition: WorkflowDefinition) -> WorkflowMetadata: ...
    def execute(
        self, workflow_id: str, inputs: dict[str, str],
        trigger_type: TriggerType,
    ) -> WorkflowExecutionResult: ...
    def pause(self, execution_id: str) -> WorkflowExecutionResult: ...
    def resume(self, execution_id: str) -> WorkflowExecutionResult: ...
    def cancel(self, execution_id: str) -> WorkflowExecutionResult: ...
    def get_health(self, workflow_id: str) -> WorkflowHealthReport | None: ...
    def list_workflows(self) -> tuple[WorkflowMetadata, ...]: ...
