from __future__ import annotations

from typing import Protocol

from jarvis_extensions.models import (
    CapabilityDefinition,
    CapabilityType,
    CompatibilityIssue,
    CompatibilityLevel,
    CompatibilityReport,
    DependencyDefinition,
    ExtensionHealth,
    ExtensionManifest,
    ExtensionMetadata,
    ExtensionStatus,
    ExtensionType,
    IsolationPolicy,
    PermissionRequest,
    PermissionScope,
    VersionInfo,
)


class ExtensionRegistry(Protocol):
    def register(self, manifest: ExtensionManifest) -> ExtensionMetadata: ...
    def get(self, extension_id: str) -> ExtensionMetadata | None: ...
    def list(self) -> tuple[ExtensionMetadata, ...]: ...
    def list_by_status(self, status: ExtensionStatus) -> tuple[ExtensionMetadata, ...]: ...
    def list_by_type(self, ext_type: ExtensionType) -> tuple[ExtensionMetadata, ...]: ...
    def update(self, metadata: ExtensionMetadata) -> None: ...
    def remove(self, extension_id: str) -> None: ...
    def contains(self, extension_id: str) -> bool: ...


class ManifestValidator(Protocol):
    def validate(self, manifest: ExtensionManifest) -> tuple[CompatibilityIssue, ...]: ...
    def validate_platform_compatibility(
        self,
        manifest: ExtensionManifest,
        platform_version: VersionInfo,
    ) -> CompatibilityReport: ...


class DependencyManager(Protocol):
    def resolve(
        self,
        extension_id: str,
        dependencies: tuple[DependencyDefinition, ...],
        registry: ExtensionRegistry,
    ) -> tuple[CompatibilityIssue, ...]: ...
    def validate_circular(
        self,
        extension_id: str,
        dependencies: tuple[DependencyDefinition, ...],
        registry: ExtensionRegistry,
    ) -> tuple[CompatibilityIssue, ...]: ...


class CompatibilityEngine(Protocol):
    def check_extension_compatibility(
        self,
        manifest: ExtensionManifest,
        platform_version: VersionInfo,
    ) -> CompatibilityReport: ...
    def check_version_compatibility(
        self,
        version: VersionInfo,
        constraint: str,
    ) -> CompatibilityLevel: ...
    def check_contract_compatibility(
        self,
        provided: CapabilityDefinition,
        expected: CapabilityDefinition,
    ) -> CompatibilityLevel: ...


class CapabilityRegistry(Protocol):
    def register_capability(
        self,
        extension_id: str,
        capability: CapabilityDefinition,
    ) -> None: ...
    def unregister_capability(self, extension_id: str, identifier: str) -> None: ...
    def get_capability(self, identifier: str) -> CapabilityDefinition | None: ...
    def list_capabilities(
        self,
        capability_type: CapabilityType | None = None,
    ) -> tuple[tuple[str, CapabilityDefinition], ...]: ...
    def list_extension_capabilities(
        self,
        extension_id: str,
    ) -> tuple[CapabilityDefinition, ...]: ...
    def clear_extension(self, extension_id: str) -> None: ...


class LifecycleManager(Protocol):
    def transition(
        self,
        metadata: ExtensionMetadata,
        target: ExtensionStatus,
    ) -> ExtensionMetadata: ...
    def can_transition(self, current: ExtensionStatus, target: ExtensionStatus) -> bool: ...
    def valid_transitions(self, current: ExtensionStatus) -> tuple[ExtensionStatus, ...]: ...


class PermissionManager(Protocol):
    def grant(self, extension_id: str, permission: PermissionRequest) -> None: ...
    def revoke(self, extension_id: str, scope: PermissionScope) -> None: ...
    def check(self, extension_id: str, scope: PermissionScope) -> bool: ...
    def list_permissions(self, extension_id: str) -> tuple[PermissionRequest, ...]: ...
    def revoke_all(self, extension_id: str) -> None: ...


class IsolationManager(Protocol):
    def set_policy(self, extension_id: str, policy: IsolationPolicy) -> None: ...
    def get_policy(self, extension_id: str) -> IsolationPolicy | None: ...
    def check_capability_allowed(
        self,
        extension_id: str,
        capability_type: CapabilityType,
    ) -> bool: ...
    def remove_policy(self, extension_id: str) -> None: ...


class VersionManager(Protocol):
    def compare(self, a: VersionInfo, b: VersionInfo) -> int: ...
    def is_compatible(self, version: VersionInfo, constraint: str) -> bool: ...
    def suggest_upgrade(
        self,
        current: VersionInfo,
        available: tuple[VersionInfo, ...],
    ) -> VersionInfo | None: ...
    def is_deprecated(
        self,
        version: VersionInfo,
        deprecation_map: dict[str, VersionInfo],
    ) -> bool: ...


class HealthMonitor(Protocol):
    def record_activation(self, extension_id: str) -> ExtensionHealth: ...
    def record_failure(self, extension_id: str, message: str) -> ExtensionHealth: ...
    def get_health(self, extension_id: str) -> ExtensionHealth | None: ...
    def list_unhealthy(self) -> tuple[ExtensionHealth, ...]: ...
    def reset_health(self, extension_id: str) -> None: ...


class EventIntegration(Protocol):
    def subscribe(
        self,
        extension_id: str,
        event_type: str,
        handler_id: str,
    ) -> None: ...
    def unsubscribe(self, extension_id: str, event_type: str) -> None: ...
    def list_subscriptions(self, extension_id: str) -> tuple[tuple[str, str], ...]: ...
    def unsubscribe_all(self, extension_id: str) -> None: ...


class ExtensionKernel(Protocol):
    def discover(self, manifest: ExtensionManifest) -> ExtensionMetadata: ...
    def install(self, extension_id: str) -> ExtensionMetadata: ...
    def activate(self, extension_id: str) -> ExtensionMetadata: ...
    def deactivate(self, extension_id: str) -> ExtensionMetadata: ...
    def disable(self, extension_id: str) -> ExtensionMetadata: ...
    def enable(self, extension_id: str) -> ExtensionMetadata: ...
    def remove(self, extension_id: str) -> ExtensionMetadata | None: ...
    def update(
        self,
        extension_id: str,
        new_manifest: ExtensionManifest,
    ) -> ExtensionMetadata: ...
    def get_metadata(self, extension_id: str) -> ExtensionMetadata | None: ...
    def list_extensions(
        self,
        status: ExtensionStatus | None = None,
    ) -> tuple[ExtensionMetadata, ...]: ...
    def get_health(self, extension_id: str) -> ExtensionHealth | None: ...
