"""Workspace repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.workspace.models import (
    Project,
    ResourceAllocation,
    Workspace,
    WorkspaceMembership,
)


class WorkspaceRepository(Protocol):
    def save(self, workspace: Workspace) -> None: ...
    def get(self, workspace_id: UUID) -> Workspace | None: ...
    def delete(self, workspace_id: UUID) -> None: ...
    def list_by_org(self, org_id: UUID) -> list[Workspace]: ...
    def add_member(self, workspace_id: UUID, membership: WorkspaceMembership) -> None: ...
    def remove_member(self, workspace_id: UUID, user_id: str) -> None: ...
    def get_members(self, workspace_id: UUID) -> list[WorkspaceMembership]: ...
    def save_project(self, project: Project) -> None: ...
    def get_project(self, project_id: UUID) -> Project | None: ...
    def list_projects(self, workspace_id: UUID) -> list[Project]: ...
    def set_allocation(self, allocation: ResourceAllocation) -> None: ...
    def get_allocation(self, workspace_id: UUID, resource_type: str) -> ResourceAllocation | None: ...
