"""Analytics repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.analytics.models import (
    DashboardWidget,
    MetricSnapshot,
    Report,
    ReportDefinition,
)


class AnalyticsRepository(Protocol):
    def save_report_definition(self, definition: ReportDefinition) -> None: ...
    def get_report_definition(self, definition_id: UUID) -> ReportDefinition | None: ...
    def list_report_definitions(self) -> list[ReportDefinition]: ...
    def save_report(self, report: Report) -> None: ...
    def list_reports(self, org_id: UUID, category: str | None = None) -> list[Report]: ...
    def save_metric(self, metric: MetricSnapshot) -> None: ...
    def query_metrics(self, metric_name: str, org_id: UUID) -> list[MetricSnapshot]: ...
    def save_widget(self, widget: DashboardWidget) -> None: ...
    def list_widgets(self) -> list[DashboardWidget]: ...
