"""Collaboration repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.collaboration.models import (
    Approval,
    Discussion,
    DiscussionReply,
    ReviewWorkflow,
    SharedKnowledge,
    SharedProject,
)


class CollaborationRepository(Protocol):
    def save_shared_project(self, project: SharedProject) -> None: ...
    def get_shared_project(self, project_id: UUID) -> SharedProject | None: ...
    def list_shared_projects(self, workspace_id: UUID) -> list[SharedProject]: ...
    def save_shared_knowledge(self, knowledge: SharedKnowledge) -> None: ...
    def list_shared_knowledge(self) -> list[SharedKnowledge]: ...
    def save_discussion(self, discussion: Discussion) -> None: ...
    def list_discussions(self) -> list[Discussion]: ...
    def save_reply(self, reply: DiscussionReply) -> None: ...
    def list_replies(self, discussion_id: UUID) -> list[DiscussionReply]: ...
    def save_workflow(self, workflow: ReviewWorkflow) -> None: ...
    def get_workflow(self, workflow_id: UUID) -> ReviewWorkflow | None: ...
    def list_workflows(self) -> list[ReviewWorkflow]: ...
    def save_approval(self, approval: Approval) -> None: ...
    def list_approvals(self, workflow_id: UUID) -> list[Approval]: ...
