"""Resource management repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.resource_management.models import (
    ComputeAllocation,
    Quota,
    ResourceUsage,
    StorageAllocation,
    UsagePolicy,
)


class ResourceRepository(Protocol):
    def save_quota(self, quota: Quota) -> None: ...
    def get_quota(self, org_id: UUID, resource_type: str, resource_name: str) -> Quota | None: ...
    def list_quotas(self, org_id: UUID) -> list[Quota]: ...
    def record_usage(self, usage: ResourceUsage) -> None: ...
    def get_usage(self, org_id: UUID, resource_type: str) -> list[ResourceUsage]: ...
    def save_usage_policy(self, policy: UsagePolicy) -> None: ...
    def list_usage_policies(self) -> list[UsagePolicy]: ...
    def set_compute_allocation(self, allocation: ComputeAllocation) -> None: ...
    def get_compute_allocation(self, workspace_id: UUID) -> ComputeAllocation | None: ...
    def set_storage_allocation(self, allocation: StorageAllocation) -> None: ...
    def get_storage_allocation(self, workspace_id: UUID) -> StorageAllocation | None: ...
