"""Organization repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.organization.models import (
    Organization,
    OrganizationHierarchy,
    OrganizationMember,
)


class OrganizationRepository(Protocol):
    def save(self, org: Organization) -> None: ...
    def get(self, org_id: UUID) -> Organization | None: ...
    def delete(self, org_id: UUID) -> None: ...
    def list(self) -> list[Organization]: ...
    def add_member(self, org_id: UUID, member: OrganizationMember) -> None: ...
    def remove_member(self, org_id: UUID, user_id: str) -> None: ...
    def get_members(self, org_id: UUID) -> list[OrganizationMember]: ...
