"""Governance repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.governance.models import (
    ComplianceControl,
    DataGovernanceRule,
    GovernancePolicy,
    PolicyScope,
    RetentionPolicy,
)


class GovernanceRepository(Protocol):
    def save_policy(self, policy: GovernancePolicy) -> None: ...
    def get_policy(self, policy_id: UUID) -> GovernancePolicy | None: ...
    def list_policies(self, scope: PolicyScope | None = None) -> list[GovernancePolicy]: ...
    def delete_policy(self, policy_id: UUID) -> None: ...
    def save_data_rule(self, rule: DataGovernanceRule) -> None: ...
    def list_data_rules(self) -> list[DataGovernanceRule]: ...
    def save_retention_policy(self, policy: RetentionPolicy) -> None: ...
    def list_retention_policies(self) -> list[RetentionPolicy]: ...
    def save_compliance_control(self, control: ComplianceControl) -> None: ...
    def list_compliance_controls(self, framework: str | None = None) -> list[ComplianceControl]: ...
