"""User administration repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.user.models import AccessReview, EnterpriseUser, Invitation


class EnterpriseUserRepository(Protocol):
    def save_user(self, user: EnterpriseUser) -> None: ...
    def get_user(self, user_id: str) -> EnterpriseUser | None: ...
    def list_users(self, org_id: UUID) -> list[EnterpriseUser]: ...
    def save_invitation(self, invitation: Invitation) -> None: ...
    def get_invitation(self, invitation_id: UUID) -> Invitation | None: ...
    def list_invitations(self, org_id: UUID) -> list[Invitation]: ...
    def save_access_review(self, review: AccessReview) -> None: ...
    def list_access_reviews(self, org_id: UUID) -> list[AccessReview]: ...
