"""Billing and licensing repository contracts."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from jarvis_enterprise.billing.models import (
    CostReport,
    License,
    Subscription,
    SubscriptionPlan,
    UsageRecord,
)


class BillingRepository(Protocol):
    def save_plan(self, plan: SubscriptionPlan) -> None: ...
    def get_plan(self, plan_id: UUID) -> SubscriptionPlan | None: ...
    def list_plans(self) -> list[SubscriptionPlan]: ...
    def save_subscription(self, subscription: Subscription) -> None: ...
    def get_subscription(self, org_id: UUID) -> Subscription | None: ...
    def save_license(self, license_: License) -> None: ...
    def get_license(self, org_id: UUID) -> License | None: ...
    def record_usage(self, record: UsageRecord) -> None: ...
    def get_usage(self, org_id: UUID, period: str) -> list[UsageRecord]: ...
    def save_cost_report(self, report: CostReport) -> None: ...
    def get_cost_report(self, org_id: UUID, period: str) -> CostReport | None: ...
