from __future__ import annotations

from typing import Protocol

from jarvis_agents.models import (
    AgentCapability,
    AgentCommunicationRequest,
    AgentCommunicationResponse,
    AgentEvent,
    AgentGoal,
    AgentHealthReport,
    AgentMetadata,
    AgentPermission,
    AgentPolicy,
    AgentPolicyScope,
    AgentStatus,
    AgentTask,
    AgentTaskResult,
)


class AgentRegistry(Protocol):
    def register(self, agent: AgentMetadata) -> None: ...

    def update(self, agent: AgentMetadata) -> None: ...

    def get(self, identifier: str) -> AgentMetadata | None: ...

    def list(self) -> tuple[AgentMetadata, ...]: ...

    def list_by_status(self, status: AgentStatus) -> tuple[AgentMetadata, ...]: ...

    def list_by_capability(self, capability_name: str) -> tuple[AgentMetadata, ...]: ...

    def deregister(self, identifier: str) -> None: ...


class LifecycleManager(Protocol):
    def initialize(self, identifier: str) -> None: ...

    def transition(self, identifier: str, to: AgentStatus) -> AgentMetadata: ...

    def current(self, identifier: str) -> AgentStatus | None: ...

    def can_transition(self, from_status: AgentStatus, to: AgentStatus) -> bool: ...


class CapabilityManager(Protocol):
    def register_capability(self, capability: AgentCapability) -> None: ...

    def get_capability(self, name: str) -> AgentCapability | None: ...

    def list_capabilities(self) -> tuple[AgentCapability, ...]: ...

    def has_capability(self, agent: AgentMetadata, capability_name: str) -> bool: ...

    def find_agents_with_capability(
        self,
        agents: tuple[AgentMetadata, ...],
        capability_name: str,
    ) -> tuple[AgentMetadata, ...]: ...


class PermissionManager(Protocol):
    def check_permission(
        self,
        agent: AgentMetadata,
        resource: str,
        access: str,
        scope: str = "*",
    ) -> bool: ...

    def grant_permission(self, identifier: str, permission: AgentPermission) -> None: ...

    def revoke_permission(self, identifier: str, resource: str, scope: str = "*") -> None: ...


class GoalManager(Protocol):
    def create_goal(self, goal: AgentGoal) -> AgentGoal: ...

    def update_progress(self, goal_id: str, progress: float) -> AgentGoal: ...

    def update_status(self, goal_id: str, status: str) -> AgentGoal: ...

    def get_goal(self, goal_id: str) -> AgentGoal | None: ...

    def list_goals(self) -> tuple[AgentGoal, ...]: ...

    def list_goals_by_status(self, status: str) -> tuple[AgentGoal, ...]: ...


class TaskManager(Protocol):
    def create_task(self, task: AgentTask) -> AgentTask: ...

    def assign_task(self, task_id: str, agent_id: str) -> AgentTask: ...

    def complete_task(self, task_id: str, result: AgentTaskResult) -> AgentTask: ...

    def fail_task(self, task_id: str, error: str) -> AgentTask: ...

    def retry_task(self, task_id: str) -> AgentTask: ...

    def get_task(self, task_id: str) -> AgentTask | None: ...

    def list_tasks(self) -> tuple[AgentTask, ...]: ...

    def list_tasks_by_agent(self, agent_id: str) -> tuple[AgentTask, ...]: ...

    def list_tasks_by_status(self, status: str) -> tuple[AgentTask, ...]: ...


class CommunicationBus(Protocol):
    def send_request(self, request: AgentCommunicationRequest) -> None: ...

    def send_response(self, response: AgentCommunicationResponse) -> None: ...

    def publish_event(self, event: AgentEvent) -> None: ...

    def pending_requests(self, agent_id: str) -> tuple[AgentCommunicationRequest, ...]: ...

    def pending_responses(self, correlation_id: str) -> tuple[AgentCommunicationResponse, ...]: ...

    def pending_events(self, agent_id: str) -> tuple[AgentEvent, ...]: ...


class MemoryInterface(Protocol):
    def store(self, agent_id: str, key: str, value: str) -> None: ...

    def retrieve(self, agent_id: str, key: str) -> str | None: ...

    def search(self, agent_id: str, query: str) -> tuple[str, ...]: ...

    def delete(self, agent_id: str, key: str) -> None: ...


class KnowledgeInterface(Protocol):
    def query(self, agent_id: str, query: str) -> tuple[str, ...]: ...

    def get_document(self, agent_id: str, document_id: str) -> str | None: ...

    def search(self, agent_id: str, query: str, workspace: str) -> tuple[str, ...]: ...


class ToolInterface(Protocol):
    def execute(self, agent_id: str, tool_name: str, parameters: str) -> str: ...

    def list_available(self, agent_id: str) -> tuple[str, ...]: ...

    def check_access(self, agent_id: str, tool_name: str) -> bool: ...


class HealthMonitor(Protocol):
    def record_heartbeat(
        self,
        agent_id: str,
        status: AgentStatus,
        metadata: dict[str, str] | None = None,
    ) -> AgentHealthReport: ...

    def record_failure(self, agent_id: str, error_message: str) -> AgentHealthReport: ...

    def get_report(self, agent_id: str) -> AgentHealthReport | None: ...

    def list_reports(self) -> tuple[AgentHealthReport, ...]: ...

    def list_unhealthy(self) -> tuple[AgentHealthReport, ...]: ...


class PolicyEngine(Protocol):
    def register_policy(self, scope: AgentPolicyScope, policy: AgentPolicy) -> None: ...

    def resolve(self, scope: AgentPolicyScope) -> AgentPolicy: ...

    def evaluate(self, *, agent: AgentMetadata, policy: AgentPolicy) -> tuple[str, ...]: ...
